### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by mfuxi** [bruj0/vault_jenkins#1]
I went through the instruction but i'm keep getting:
```
Error reading secret/<someSecret>: Error making API request.

URL: Get http://127.0.0.1:8200/v1/secret/<someSecret>
Code: 403. Errors:

* pemission denied
```

Any idea what am I doing wrong?

**Comment by mfuxi** [comment]
After further debugging I understand my problem, I tried instead of using this token:
`export JOB_VAULT_TOKEN=$(./vault write -field=token auth/approle/login role_id=${ROLE_ID}   secret_id=${SECRET_ID})`

To use the root token, and then it worked.. this is of course bad practice, I don't understand why it doesn't work with the token created above.. any idea?

**Comment by bruj0** [comment]
Are you getting the SECRET_ID correctly? with
export SECRET_ID=$(./vault write -field=secret_id -f auth/approle/role/java-example/secret-id)

Also check that you are using the correct role-id, generated by: 
$ vault token-create -policy=jenkins

With both of this, you can get a token that will let you access the secrets for your app.

**Comment by mfuxi** [comment]
My bad, I had a mistake there when running the commands..
But you got some several wrong configurations there in your README.md
for instance:
`export JOB_VAULT_TOKEN` should be `export VAULT_TOKEN`
